name: github-actions/develop/lint
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  lint:
    name: Lint and Type check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-16-${{ hashFiles('yarn.lock') }}

      - name: Install packages
        run: yarn

      - name: Run syntax check
        run: yarn type-check

      - name: Run lint
        run: yarn lint
