name: github-actions/develop/coverage
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    name: Test and Coverage
    runs-on: ubuntu-latest
    # env:
    #   GRAPHQL_SERVER: http://gateway:7000/graphql
    #   GOOGLE_OAUTH_CLIENT_ID:

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-16-${{ hashFiles('yarn.lock') }}

      - name: Install packages
        run: yarn

      - name: Run test
        run: yarn test:coverage
        env:
          CI: true
