name: github-actions/develop/build
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ${{ secrets.HARBOR_URL }}
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    # env:
    #   GRAPHQL_SERVER: http://gateway:7000/graphql
    #   GOOGLE_OAUTH_CLIENT_ID:

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: node-${{ hashFiles('yarn.lock') }}
          restore-keys: node-

      - name: Install packages
        run: yarn

      - name: Run build
        run: yarn build

      - name: Run test
        run: yarn test
        env:
          CI: true
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USER_ID }}
          password: ${{ secrets.HARBOR_USER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
